version: '3.8'

services:
  udrop-backend:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: udrop-backend
    ports:
      - "8000:8000"
    volumes:
      - ../udrop.db:/app/udrop.db
      - ../storage:/app/storage
      - ../logs:/app/logs
    env_file:
      - ../.env
    restart: unless-stopped
